### ISSUE TITLE
Organize Page Tree

### ISSUE THREAD

**Issue by salirmo** [MRezaSafari/AwesomeFrontend#10]
It is better to prioritize each topic based on level.
for example, this page is not organized. 
https://github.com/MRezaSafari/AwesomeFrontend/blob/main/topics/javascript.md

I suggest sorting it from beginner to advance. If you agree, I can help with sorting.

**Comment by reza-salemi** [comment]
Also, you can sort it from advanced level to beginner. But now, It is not organized.

**Comment by MRezaSafari** [comment]
Thank you for your suggestion dear Reza.
But I think we should keep this sorting and add the new topic on top of previous ones.
this way, the newest topics always stay on top.
