### ISSUE TITLE
Request for separation by topic

### ISSUE THREAD

**Issue by mojtaba-afraz** [MRezaSafari/AwesomeFrontend#2]
I think if the links of each technology are placed in different files, it will add more accessibility and readability

**_If you wish, I can send you my offer under a PR_**

**Comment by mojtaba-afraz** [comment]
Yes, you are right
But I'm thinking about the future and when this list goes on and on scrolls a lot
@MRezaSafari

**Comment by MRezaSafari** [comment]
Completely agree.
in that case, I will create a github page with search capabilities and category filtering.

how about that?

**Comment by mojtaba-afraz** [comment]
I think these two are separated
It is better to look at this as a project
Most of all I mean for the scalability of this repository
But I also welcome the github page idea and am ready to participate

**Comment by MRezaSafari** [comment]
take a look at the new structure please and leave your opinion.
also, I changed the project name to AwesomeFrontend
